# Generated by Django 4.1 on 2023-09-29 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Board",
            new_name="board",
        ),
    ]
