# Generated by Django 4.1 on 2023-10-09 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_alter_board_content_alter_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(5, "다섯글자 이상은 입력하십시오")
                ],
            ),
        ),
    ]
